### ISSUE TITLE
shadowsocks hangs with stopping

### ISSUE THREAD

**Issue by KarlM256** [shadowsocks/shadowsocks-android#1122]
* Android version: 6.0.1
* Device: Motorola G4 Plus 64 GB
* Shadowsocks version: 4.0.2 (4.0.1 also)
* Last version that did not exhibit the issue (if applicable): 3.3.1

### Configuration

_Put an `x` inside the [ ] that applies._

* [x] IPv4 server address
* [ ] IPv6 server address
* [x] Client IPv4 availability
* [ ] Client IPv6 availability
* Local port: 1080
* Encrypt method: AES-128-CTR
* [ ] One-time authentication
* Route
  * [ ] All
  * [z] Bypass LAN
  * [ ] Bypass China
  * [ ] Bypass LAN & China
  * [ ] GFW List
  * [ ] China List
  * [ ] Custom rules
* [ ] IPv6 route
* [ ] Per-App Proxy
  * [ ] Bypass mode
* [x] UDP Forwarding
* Plugin configuration (if applicable):
* [ ] Auto Connect
* [ ] TCP Fast Open
* [ ] NAT mode

### What did you do?
Start it. Then Stop it from the green paper airplane icon.

### What did you expect to see?
I expected it to stop and be ready to restart.

### What did you see instead?
It hung with the orange ring going around the green paper airplane. Text saying shutting down.
VPN icon still in the top android status bar.
I had to force stop the app.

**Comment by KarlM256** [comment]
Changing the encryption to AES-128-GCM made no difference.
Attaching a screenshot

**Comment by KarlM256** [comment]
![screenshot_20170212-140504](https://cloud.githubusercontent.com/assets/13839705/22866582/d25f6296-f12d-11e6-8117-4c1071272009.jpg)

**Comment by KarlM256** [comment]
Can anyone else reproduce this?

**Comment by madeye** [comment]
Try uninstall and reinstall the app.

**Comment by KarlM256** [comment]
Hi...

Tried uninstall and reinstall the app. No change..same problem.

Shadowsocks-Android 4.0.3
Shadowsocks-libev 3.0.2, although that does not seem to matter.

Tried a Nexus 6 running Android 7.0 and it worked fine.

I'll try it on another phone tonight.

Any other thoughts?

Thanks,

...Karl

**Comment by Mygod** [comment]
Attach logcat if possible.

**Comment by KarlM256** [comment]
I tried it on an LG G Flex 2 running android 5.1.1 and it works fine. (Frustrating)

**Comment by hanson-l** [comment]
I also meet this problem on Samsung S6 running android 6.0.1.

**Comment by KarlM256** [comment]
Do you mean that you were using shadowsocks-android with the kcptun plugin? If so, do you have the same problem without using the plugin? Can you disable the kcptun plugin on your android device and try it again?

**Comment by hanson-l** [comment]
Oh, the 4.0.2 ver. runs normally.

**Comment by V-E-O** [comment]
Came across same issue this morning with 4.0.3 and obfs plugin enabled. Solve it by clearing the SS activity.

**Comment by lingbaoboy** [comment]
貌似开启obfs会出现

**Comment by KarlM256** [comment]
Here is a logcat of starting shadowsocks, having it hang and killing it. The log is filtered for lines with shadowsocks.

[shadowsocks.txt](https://github.com/shadowsocks/shadowsocks-android/files/805434/shadowsocks.txt)

**Comment by Mygod** [comment]
You've filtered some important information. Try again.

**Comment by KarlM256** [comment]
Here is a new logcat without the heavy filtering.

[shadowsocks.txt](https://github.com/shadowsocks/shadowsocks-android/files/805639/shadowsocks.txt)

**Comment by Mygod** [comment]
Hmm... For now I'm suspecting https://github.com/shadowsocks/shadowsocks-android/commit/8d1f2da1f075957a1d87d409a8345d29c590b648 is causing this issue.

**Comment by Mygod** [comment]
@madeye What do you think? This problem looks like a third-party bug where SIGTERM is ignored for some reason. We could add a timeout and do SIGKILL instead but that would raise another problem for terminating plugin processes.

Another workaround is to maybe somehow kill `:bg` process group when doing a reset. And when users do a reset they can be sure that everything is terminated.

**Comment by madeye** [comment]
I think a delay of `process.destroy()` would do the trick. To ensure the process killed properly, we may first send SIGTERM, wait for 1 second then send SIGKILL.

I think all the latest plugins support detecting the detach or a parent process. So this change would not bring any side effect.

**Comment by Mygod** [comment]
1 second for each process would add up to 4 seconds for service to shut down if it turns out it's their Android system that has bugged out. If we're really going to take this approach, how about half a sec? Or use a process pool to manage these processes which would involve even more work.

Another thing is SIGTERM is always used since Android 7.0 so I assume it's a bug of their ROM. I still think the better solution is ~not to fix this device-specific issue~ to kill the process group when user presses Reset and buggy ROMs can always reset if something goes wrong in `:bg`.

**Comment by madeye** [comment]
@Mygod OK, to keep things clean, let's just kill `:bg` in `reset` action for now.

Also, let's see if there are more similar issues after the first stable release pushed to more users.

**Comment by KarlM256** [comment]
I have a new logcat with kcptun. However, uploading the txt file fails with the message "Something went really wrong, and we can’t process that file. Try again.".

**Comment by KarlM256** [comment]
[log.txt](https://github.com/shadowsocks/shadowsocks-android/files/809137/log.txt)

The upload worked from my phone.

**Comment by madeye** [comment]
@Mygod According to some feedbacks in Google Play, this issue seems to happen on many Moto devices. 

I implemented a `waitpid` with the `WNOHANG` flag to have a timeout here via a61b03c. After some quick tests, it seems to work well.

**Comment by madeye** [comment]
@KarlM256 Try this APK https://dl.dropboxusercontent.com/u/4356689/shadowsocks-nightly-4.1.0.apk

**Comment by KarlM256** [comment]
Hi...

I just tried the 4.1.0 apk. When I use shadowsocks without any plugins, the change works fine. I can see the delay for the timeout, but it disconnects fine. When I run shadowsocks with the kcptun plugin, it still hangs. The symptoms are slightly different. If I force stop shadowsocks, that disconnects as before. However, previously I could also disconnect by first touching the paper airplane icon, then I could connect to private tunnel with the openvpn app. Shadowsocks would give a dialog box with "Unfortunately shadowsocks has stopped working" I would then click ok and disconnect openvpn. After that, shadowsocks was disconnected again as I desired.

Now only the force stop method works (when kcptun is used). Connecting with openvpn does not cause the dialog box and it does not cause shadowsocks to disconnect.

If additional logs would be useful, please describe what you would like to see.

**Comment by KarlM256** [comment]
Hi...

I have a question. The hanging problem started only with recent shadowsocks-android versions. How did you terminate the background task differently in the past vs how you terminate it now?

Thanks,

...Karl

**Comment by madeye** [comment]
Try this kcptun: https://dl.dropboxusercontent.com/u/4356689/kcptun-nightly-0.0.4.apk

**Comment by KarlM256** [comment]
With both of your recent apks, shadowsocks starts and stops with and without kcptun. Nice job working around my bad Moto factory ROM.

Is the obfuscation plugin and server in working order? Should I set up to try them yet?

**Comment by madeye** [comment]
You can also try simple-obfs. It should work now.

**Comment by Mygod** [comment]
I did some research and unfortunately [process group is introduced](https://android.googlesource.com/platform/frameworks/base/+/0161bbc%5E!/) back in Lollipop. And it seems this bug can be worked around by using Reset already.

**Comment by Mygod** [comment]
Try 8677308? @madeye

**Comment by madeye** [comment]
@Mygod It crashed on Android 4.4.

```
E/dalvikvm( 2345): Fatal error: ProcessManager$ProcessImpl.exitValue not found
```

Maybe we'd better not use private API here.

**Comment by madeye** [comment]
Hmm, it turns out to be a typo. Fixed via d5d6740.

**Comment by madeye** [comment]
@KarlM256 Could you try this APK https://www.dropbox.com/s/p1dvtvq99tig006/shadowsocks-nightly-4.1.0.apk again?

**Comment by KarlM256** [comment]
The latest version looks good. I just installed and tested with shadowsocks alone, with KCP and with OBFS. All three worked. Just to be clear...The previous apk and this one were both named 4.1.0. I did an install and it succeeded, but I can't independently verify the version of my apk.

**Comment by madeye** [comment]
@KarlM256 Thanks! The latest one should override the previous one. I think they both works for you now.

**Comment by KarlM256** [comment]
With the new plugin approach, clearly the UDP forwarding option can not work with a plugin because the port number for the plain shadowsocks server is unknown.

However I have noticed that SIP connections fail to work without UDP forwarding. I can only try this without using a plugin. That is, unless I use the android client without a plugin and enable UDP forwarding, SIP connections fail. If I enable UPD forwarding and do not use a plugin, SIP connections work.

**Comment by KarlM256** [comment]
From issue #1022, I want to clarify, does shadowsocks do UDP over TCP when UDP forwarding is not selected?

**Comment by madeye** [comment]
> With the new plugin approach, clearly the UDP forwarding option can not work with a plugin because the port number for the plain shadowsocks server is unknown.

The UDP port is still the same. The only exception is KCPTUN, which requires a trick here: https://github.com/shadowsocks/shadowsocks-android/issues/1090#issuecomment-274404651

> However I have noticed that SIP connections fail to work without UDP forwarding. I can only try this without using a plugin. That is, unless I use the android client without a plugin and enable UDP forwarding, SIP connections fail. If I enable UPD forwarding and do not use a plugin, SIP connections work.

SIP is a UDP protocol, So, you need to enable UDP forwarding.

> From issue #1022, I want to clarify, does shadowsocks do UDP over TCP when UDP forwarding is not selected?

Nope, disabling UDP means drop all UDP packets locally.

**Comment by KarlM256** [comment]
So if UDP forwarding is selected, are the UDP packets sent through the plugin? Are UDP packets obfuscated? What does KCP do with UDP packets?

**Comment by madeye** [comment]
> So if UDP forwarding is selected, are the UDP packets sent through the plugin? Are UDP packets obfuscated? What does KCP do with UDP packets?

All UDP traffic should bypass the SIP003 plugin.

**Comment by KarlM256** [comment]
Wouldn't it make sense to obfuscate UDP traffic as well as TCP?

**Comment by madeye** [comment]
> Wouldn't it make sense to obfuscate UDP traffic as well as TCP?

No plan for this.

**Comment by KarlM256** [comment]
When using kcptun with incorrect options shadowsocks android hangs on shutdown. I had the u option in the plugin options in android. Testing the connection timed out and shutting down the connection hung, requiring a force stop.
